rails/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :users, only: %i[index show]
  get ':id', to: 'user#show', as: :user_root

  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

rails/app/models/ability.rb
# frozen_string_literal: true

# CanCan ability
class Ability
  include CanCan::Ability

  def initialize(user = nil)
    user ||= User.new # for guest
    can :index, :welcome
    return if user.new_record?
    can :read, User, id: user.id
    return unless user.superuser?
    can :read, User
    return unless user.role?(:deity)
    can :index, :users
  end
end

rails/app/models/application_record.rb
# frozen_string_literal: true

# It's pretty common for folks to monkey patch ActiveRecord::Base to
# work around an issue or introduce extra functionality. Instead of
# shoving even more stuff in ActiveRecord::Base, ApplicationRecord can
# hold all those custom work the apps may need.
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/app/models/assignment.rb
# frozen_string_literal: true

# User/Role relation
class Assignment < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

rails/app/models/player.rb
# frozen_string_literal: true

# Player record, will hold all player information
class Player < ApplicationRecord
  belongs_to :user

  validates :username, presence: true, uniqueness: true
end

rails/app/models/role.rb
# frozen_string_literal: true

# Roles for users
class Role < ApplicationRecord
  ROLES = %w[player storyteller deity].freeze

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :name, inclusion: {
    in: ROLES,
    message: '"%{value}" is not a valid role',
    case_sensitive: false
  }

  has_many :assignments
  has_many :users, through: :assignments

  def self.superuser
    ROLES[1, 2]
  end
end

rails/app/models/user.rb
# frozen_string_literal: true

# Log in user.
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :omniauthable
  devise :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :timeoutable, :lockable

  has_one :player
  has_many :assignments
  has_many :roles, through: :assignments

  def username
    player ? player.username : email
  end

  def role?(role)
    roles.any? { |r| r.name.underscore == role.to_s }
  end

  def superuser?
    (Role.superuser & roles.map(&:name)).present?
  end
end

rails/app/controllers/application_controller.rb
# frozen_string_literal: true

# Base ApplicationController
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    url = current_user.new_record? ? root_url : user_url(current_user)
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to url, alert: exception.message }
    end
  end

  def after_sign_in_path_for(user)
    user_url(user)
  end

  def authorize_action
    authorize!(params['action'].to_sym, params['controller'].to_sym)
  end
end

rails/app/controllers/users_controller.rb
# frozen_string_literal: true

# UsersController
# GET show: the user's own homepage
# GET index: a list of users
class UsersController < ApplicationController
  before_action :authorize_action, except: [:show]
  load_and_authorize_resource only: [:show]

  def index; end

  def show
    user = find_user
    render :show, locals: { user: user }
  end

  private

  def find_user
    @user = User.find(params[:id])
  end
end

rails/app/controllers/welcome_controller.rb
# frozen_string_literal: true

# Welcome page
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :authorize_action

  def index
    render :index
  end
end

rails/app/helpers/application_helper.rb
# frozen_string_literal: true

# Module Application Helper
module ApplicationHelper
end

rails/app/helpers/users_helper.rb
# frozen_string_literal: true

# Helpers for users page
module UsersHelper
end

rails/app/helpers/welcome_helper.rb
# frozen_string_literal: true

# Helpers for welcome page
module WelcomeHelper
end

rails/app/views/layouts/application.html.slim
doctype html
html
  head
    title Play By Chat
    = csrf_meta_tags

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    - link_folder = self.respond_to?(:resource_name) ? 'devise' : 'layouts'
    div.pure-g
      = render "#{link_folder}/shared/links"
      div.pure-u-1-1
        p.notice
          = notice
        p.alert
          = alert
        == yield

rails/app/views/layouts/shared/_links.html.slim
nav.pure-u-1-1.pure-menu.pure-menu-horizontal
  span.pure-menu-heading Play By Chat
  - if user_signed_in?
    = render 'layouts/shared/loggedin_links'
  - else
    = render 'layouts/shared/loggedout_links'

rails/app/views/layouts/shared/_loggedin_links.html.slim
ul.pure-menu-list.pure-menu-horizontal
  li.pure-menu-item
    | Hello #{current_user.username}
  li.pure-menu-item
    = link_to 'My Account', user_path(current_user)
  li.pure-menu-item
    = form_tag destroy_session_path(User), method: :delete do
      = submit_tag 'Log out', class: :link

rails/app/views/layouts/shared/_loggedout_links.html.slim
ul.pure-menu-list.pure-menu-horizontal
  li.pure-menu-item
    = link_to 'Log in', new_session_path(User)
  li.pure-menu-item
    = link_to 'Sign up', new_registration_path(User)

rails/app/views/users/index.html.slim
.section
  h2 Users

rails/app/views/users/show.html.slim
h1
  | Welcome
  | &nbsp;
  = user.username

.section
  h2 Personal Data

  .pure-g
    .pure-u-1-5
    .pure-u-1-5
      label First name:
    .pure-u-2-5
      = user.firstname
    .pure-u-1-5

    .pure-u-1-5
    .pure-u-1-5
      label Last name:
    .pure-u-2-5
      = user.lastname
    .pure-u-1-5

    .pure-u-1-5
    .pure-u-1-5
      label Email:
    .pure-u-2-5
      = user.email
    .pure-u-1-5

rails/app/views/welcome/index.html.slim
h1 Ready for adventure?